services:
  crowd-management-api:
    build: .
    container_name: crowd-management-api
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_started
    external_links:
      - keycloak_app
    environment:
      - INFLUXDB_URL=http://influxdb:8181
      - MQTT_BROKER_URL=tcp://mosquitto:1883
      - KEYCLOAK_SERVER_URL=http://keycloak-app:8080
      # - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak-app:8080/realms/crowd-management
    volumes:
      - ./src/main/resources/timetable.xml:/app/src/main/resources/timetable.xml
    ports:
      - "8081:8081"

  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    restart: unless-stopped
    user: root
    ports:
      - "8181:8181"
    volumes:
      - influxdb-storage:/var/lib/influxdb3/data
    command:
      - influxdb3
      - serve
      - --without-auth
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=grafana-influxdb-08-datasource
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  influxdb-storage:
  grafana-storage:

networks:
  default:
    name: crowd-management-network
    external: true
