services:
  crowd-management-api:
    build: .
    container_name: crowd-management-api
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_started
    external_links:
      - keycloak_app
    environment:
      - INFLUXDB_URL=http://influxdb:8181
      - MQTT_BROKER_URL=tcp://mosquitto:1883
      - KEYCLOAK_SERVER_URL=http://keycloak-app:8080
      # - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak-app:8080/realms/crowd-management
    volumes:
      - ./src/main/resources/timetable.xml:/app/src/main/resources/timetable.xml
    ports:
      - "8081:8081"

  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    restart: unless-stopped
    user: root
    ports:
      - "8181:8181"
    volumes:
      - influxdb-storage:/var/lib/influxdb3/data
    command:
      - influxdb3
      - serve
      - --without-auth
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource

      - GF_SECURITY_ALLOW_EMBEDDING=true

      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Keycloak
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana-oauth
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=srktsCAfYiMYpR5Vv0dxCcCx5TsDWkDm
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email roles
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=http://localhost:8080/realms/crowd-management/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=http://keycloak-app:8080/realms/crowd-management/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=http://keycloak-app:8080/realms/crowd-management/protocol/openid-connect/userinfo

      - GF_AUTH_OAUTH_AUTO_LOGIN=true
      - GF_AUTH_SIGNOUT_REDIRECT_URL=http://localhost:8082/logout

      - GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN=true
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(realm_access.roles[*], 'theking') && 'GrafanaAdmin' || 'Viewer'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  influxdb-storage:
  grafana-storage:

networks:
  default:
    name: crowd-management-network
    external: true
