spring:
  application:
    name: crowd-management-api

  jackson:
    deserialization:
      fail-on-unknown-properties: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/crowd-management

server:
  port: 8081
  compression:
    enabled: true
#    mime-types: application/json
#    min-response-size: 1024