spring:
  application:
    name: crowd-management-api

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    datatype:
      datetime:
        write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss


  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: http://localhost:8080/realms/crowd-management
          jwk-set-uri: http://keycloak-app:8080/realms/crowd-management/protocol/openid-connect/certs

server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

keycloak:
  server-url: http://keycloak-app:8080
  realm: crowd-management
  # Service account client (Confidential, Client Credentials grant, manage-users role)
  admin-client-id: crowd-management-api
  admin-client-secret: RwCtvn3HumJpfckDaJXYGzqcG4zjTcVp

logging:
  level:
    org.eclipse.paho.client.mqttv3: DEBUG
    org.springframework.integration.mqtt: DEBUG
#    com.crowdmanagement: DEBUG
#    org.eclipse.paho: INFO
#    org.springframework.integration: INFO

mqtt:
  broker-url: "tcp://mosquitto:1883"
  client-id-prefix: spring-backend
  telemetry-topic: wiut/+/+/+/+/+/+/telemetry
  status-topic: wiut/+/+/+/+/+/+/status
  qos: 1

influxdb:
  url: http://influxdb:8181
  token: ""
  database: telemetry